#!/bin/bash

system_type=$(uname -s)
distro_type=$(uname -r)
windows_user=$(/mnt/c/Windows/System32/cmd.exe /c 'echo %USERNAME%' | sed -e 's/\r//g')

[[ $distro_type == *WSL2 ]] && yadm config local.class wsl2
[[ $distro_type == *Microsoft ]] && yadm config local.class wsl1

sudo apt update && \
sudo apt install zsh git zip unzip fzf bat jq -y

sudo apt-get install --reinstall ca-certificates

if ! command -v brew >/dev/null 2>&1; then
    NONINTERACTIVE=1
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    sudo apt-get install build-essential -y
fi

if ! command -v sdk >/dev/null 2>&1; then
    curl -s "https://get.sdkman.io" | bash
fi


if ! command -v docker >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com | sh
fi

if ! command -v devbox >/dev/null 2>&1; then
    curl -fsSL https://get.jetify.com/devbox | sh
fi

[[ $(docker version) =~ "The command 'docker' could not be found in this WSL 1 distro." ]] && curl -fsSL https://get.docker.com | sh

if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
fi

if [ ! -f "$HOME/.dircolors" ]; then
    curl https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark --output ~/.dircolors
fi

mkdir -p /mnt/c/git
ln -sf /mnt/c/git ~/git-win

echo "================================================================"
echo "First open a new shell then you can run the following:"
echo "To install NodeJs run 'nvm install 20'"

